services:

  db:
    image: mysql:8.0
    container_name: recipes_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: recipes
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: